### ISSUE TITLE
compilers, flags, C++11, oh my

### ISSUE THREAD

**Issue by uqs** [OpenXcom/OpenXcom#1267]
Hi folks

OpenXcom currently doesn't build on FreeBSD with its default shipped clang compiler. Ultimately, this is due to its insistence on putting `-Wall -Werror` *after* the user provided CXXFLAGS, which is a bug, imho.

I'm passing `"CXXFLAGS=-O2 -g -fsanitize=address -std=c++11 -Wno-unused-function"` to configure, and this shows up properly in the c++ command line, but the later `-Wall` means this "opt out" doesn't take.

Sample ps output:
```
uqs         3992 16.0  0.2   122524   81668 20  R+   21:52       0:02.32 c++ -DPACKAGE_NAME="openxcom" -DPACKAGE_TARNAME="openxcom" -DPACKAGE_VERSION="1.0.0" -DPACKAGE_STRING="openxcom 1.0.0" -DPACKAGE_BUGREPORT="openxcom@gmail.com" -DPACKAGE_URL="" -DPACKAGE="openxcom" -DVERSION="1.0.0" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_GL_GL_H=1 -DHAVE_GL=1 -I. -I/usr/local/include -O2 -g -fsanitize=address -std=c++11 -Wno-unused-function -Werror -Wall -I/usr/local/include/SDL -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE -I/usr/local/include -I/usr/local/include -D_THREAD_SAFE -pthread -I/usr/local/include/libdrm -DDATADIR="/usr/local/share/openxcom/" -O2 -g -fsanitize=address -std=c++11 -Wno-unused-function -Werror -Wall -c -o src/Basescape/openxcom-PlaceLiftState.o src/Basescape/PlaceLiftState.cpp
```

Error:
```
src/Engine/Scalers/xbrz.cpp:353:1: error: unused function 'get_a' [-Werror,-Wunused-function]                      
DEF_GETTER(a, g) DEF_GETTER(b, d) DEF_GETTER(c, a)                                                                 
^                                                                                                                                                                                                                                     
src/Engine/Scalers/xbrz.cpp:352:54: note: expanded from macro 'DEF_GETTER'                                         
#define DEF_GETTER(x, y) template <> inline uint32_t get_##x<ROT_90>(const Kernel_3x3& ker) { return ker.y; }      
                                                     ^                                                                                                                                                                                
<scratch space>:265:1: note: expanded from here                                                                    
get_a                                                                                                              
^
```

So that needs to be fixed.

Furthermore, the compilation will error out, because `std::random_shuffle` is deprecated and removed in newer C++ version. So I figured, according to the wiki, OpenXcom uses C++03 and I should compile with that, but that bombs out in the headers of yaml-cpp. So it seems to me, that the wiki should be updated and C++11 the minimum allowed standard? (why C++03 anyway? Is the win32 situation that bad, eh?)

Before sending pull requests for these issues, I'd like to know though what the chances are of them getting accepted.

Thanks much
Uli

**Comment by SupSuper** [comment]
There's no real reason to stick to C++03 but I'd like to have a clean break before changing requirements, why change what isn'tr broken you know? For example "ok after 2.0 we're only supporting C++11, so anyone that doesn't support it can version-freeze at 2.0". AFAIK yaml-cpp didn't always require C++11.

If there's any errors with flags or whatever feel free to fix them, we only really check that code passes CI.

**Comment by uqs** [comment]
You can check yaml-cpp quickly yourself by using "CXXFLAGS=-O2 -g -std=c++03" or whatever. Should bomb out during the configure phase already:

```
checking for gawk... no
checking for mawk... no
/usr/local/include/yaml-cpp/exceptions.h:100:47: error: a space is required between consecutive right angle brackets (use '> >')
    const T&, typename disable_if<is_numeric<T>>::type* = 0) {
                                              ^~
...
/usr/local/include/yaml-cpp/exceptions.h:154:33: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  Exception(const Exception&) = default;
                                ^
/usr/local/include/yaml-cpp/exceptions.h:177:45: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  ParserException(const ParserException&) = default;
                                            ^

```
etc. pp.

Seeing that C++11 is basically a decade old at this point, don't you think most platforms have suitable compiler and libc++ support these days? I don't think it needs to be tied to a major release of the game. But up to you of course.

**Comment by psacawa** [comment]
I was also unable to compile on Linux with `gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)` because of `-Werror`. Compilation works after remove the corresponding line from `configure.ac`.

**Comment by uqs** [comment]
I noticed this too late myself, but try with `./configure --disable-werror` instead :)

**Comment by SupSuper** [comment]
I'm fine with removing `-Werror` if it causes more problems than it solves.

**Comment by uqs** [comment]
I think it should stay. Folks like me probably have simply moved on to CMake instead of Autotools and we've forgotten to check ./configure for potential overrides :)

It's good that compiler warnings break the build, at least for the CI runs. Otherwise few people would take notice.

The question then becomes, why did the CI not break? Is it using compiler versions that are too old or maybe overriding -Werror?

The pull request at https://github.com/OpenXcom/OpenXcom/pull/1271/checks?check_run_id=1210725002 is currently running the build checks, and from its logs I see:

The CXX compiler identification is GNU 7.5.0 from the gcc run and
The CXX compiler identification is Clang 9.0.0 from the clang run.

Maybe it's time to bump these up another notch? Is that a CMake build btw, and does that maybe not even use -Werror?

**Comment by psacawa** [comment]
I am concerned because it seems the project does not offer a "works out of the box" experience to many people.

The nightly did not work for me: Though I eventually got it to find the data directory, it crashed on launch because it could not find an intro music file. No relevant information in `openxcom.log`. Unfamiliarity with AppImage format precluded further investigation.
When building from source, the build failed initially, as I wrote above. People unfamiliar with a C++ toolchain would give up here.

Additionally, information is scattered between several domains: `ufopaedia.org`, `openxcom.org`, their forums, this repo.  I couldn't find information about where to put translation `yaml` files.

None of this pertains directly to the project, but contributes to make it less accessible.

-an XCOM fan

**Comment by dopplershift** [comment]
Not sure how wide of a problem the build is. `cmake . && make` works out of the box perfectly on my mac.

**Comment by uqs** [comment]
Well, that's not surprising, as the `cmake` build does not add `-Werror` and also explicitly adds `-std=gnu++11` (a bit hilarious for clang, but whatever).

I don't understand why we have automake *and* cmake based build files at the same time. The CI clearly uses cmake and thus doesn't find any of the -Werror problems that people run into when using `./configure`.

So, shall we remove all autotools stuff and build on cmake? Are there platforms where autoconf is absolutely required still?

**Comment by SupSuper** [comment]
I agree the docs could use some work, but we have many contact channels where people can come and ask for support. We support `make`, `configure` and `cmake`, we support GCC, Clang and VC++. In my experience that's more accessible than most C++ projects.

The lead developers primarily use Windows, so we rely on CI to ensure we haven't broken anything on other platforms. All the other platform build files have been contributed by others, so if there are bugs or inconsistencies in them, feel free to submit fixes, as we don't really have the experience for it. Personally I don't like ´-Werror` as you've noticed, it breaks the build as compilers update. I'd rather warnings be dealt on their own time rather than rushed to make CI happy.

OpenXcom is over a decade old at this point, so I'm happy to leave well enough alone. Every option was contributed by someone needing it at some point in time, so it's impossible to know what is "absolutely required".  If you ask anyone they always want more options, not less, so we've just dutifully accepted and maintained them. If you think something should be changed or removed, make a case for it and we'll see what everyone else thinks.

**Comment by uqs** [comment]
Seeing that it leads to confusing having 2 build systems, I'd say one of them has to go! :)

I looked up the history for the CMake and Autoconf support, and cmake was committed on 2011-08-03 while autoconf came later on 2011-09-16. This is a bit odd to me. In the year 2020, I think we can autoconf rest in peace and just use CMake, which works on Win32 as well, yes?

How is the project build on Win32? I didn't see this mentioned or configured in the CI scripts. Oh, and since CI uses CMake, I really think autoconf should go (it would've avoided this long discussion :)

I'm happy to send pull request to clean this up.

**Comment by uqs** [comment]
I've been down somewhat of a rabbit hole the last few days and the fact that there are 2 CI systems at play (Travis CI and Github Actions) also added to the confusion.

Anyway, please have a look at https://github.com/uqs/OpenXcom/commits/cmake for what I'm proposing. Ignore the MacOS failure on github, somehow `homebrew update` is broken there, it works fine on Travis CI (and I have a fix for GH, but in a different branch that is still WIP).

The proposed changes:
- update documentation (I would also update the Wiki pages, if you're going forward with this)
- remove autotools, simple Makefile and PCH support
- remove redundant/conflicting flag overrides, there's now just 1 set of compiler flags (in CMake)
- remove the need to build yaml-cpp, as Ubuntu 20.04 has a modern enough package
- add an arm64 build for Travis
- remove error suppression flags that are no longer required

In my other branch, I'm working on GH Actions, the problems there are:
- same yaml-cpp problem, can be fixed by moving to 20.04 as well
- homebrew problem, easily fixed/ignored
- TODO: the "windows (clang)" build actually builds with MSVC, I have no idea why it was erroneously set up?

Please let me know what you think and if/how I should split up potential changes. I'm also curious whether you really want 2, mostly equivalent, CI solutions running at the same time. It does come with maintenance overhead after all. GH Actions would wed you to GH, but they at least have a working Windows environment. Travis CI does so too, but I have to look into what it would take to enable that.

Also, what is the published win executable being compiled with? I assume MSVC? If so, there's probably no reason to try and get a win+clang build going. In fact, doing Linux+gcc, MacOS+clang, Win+MSVC would provide coverage for 3 OSes and 3 compilers without having to go through much hoops.

Cheers
Uli

**Comment by uqs** [comment]
Folks, do you want me to send pull requests for these simplifications and bug fixes in the build system and CI workflows?

**Comment by SupSuper** [comment]
Sure, go ahead. You're messing with stuff nobody here is experienced with, so feedback will take some time. I'm only gonna find out if you "broke" someone's workflow once it's too late and the Linux developers come out of the woodwork (like this issue). :P

> Please let me know what you think and if/how I should split up potential changes. I'm also curious whether you really want 2, mostly equivalent, CI solutions running at the same time. It does come with maintenance overhead after all. GH Actions would wed you to GH, but they at least have a working Windows environment. Travis CI does so too, but I have to look into what it would take to enable that.
> 
It's the usual story. Both of them were added when they were new and shiny, no consensus could be reached on which was "better", so we just keep all of them forever just in case.

> Also, what is the published win executable being compiled with? I assume MSVC? If so, there's probably no reason to try and get a win+clang build going. In fact, doing Linux+gcc, MacOS+clang, Win+MSVC would provide coverage for 3 OSes and 3 compilers without having to go through much hoops.
> 
The automated builds use MINGW on FreeBSD, but we use MSVC on Windows locally so it would nice to have on the CI. I *think* Clang and Apple Clang are slightly different, but otherwise I agree with your assessment.
